---
title: 'Modeling for New Jerser Transit Train Delay'
author: "Jasmine Siyu Wu & Zoe Yoo"
date: "10/19/2021"
output:
  html_document:
    toc: yes
    toc_float: yes
    code_folding: hide
  ioslides_presentation:
    self-included: yes
---


<br />


## 1. Introduction & Use Case
[motivation & objectives]




```{r setup, include=TRUE, cache = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width = 10, fig.height = 5)

#Loading Libraries
library(tidyverse)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(riem)
library(lubridate)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot)
library(kableExtra)
library(jtools)     # for regression model plots
library(ggstance)
library(osmdata)
library(knitr)
library(tidycensus)
library(scales)
library(stargazer)
library(ggplot2)
library(ggpubr)
library(xtable)
library(ggmap)
library(leaflet)
library(expss)


options(scipen=999) 
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)

# functions and data directory
root.dir = "https://github.com/zoenyoo/MUSA508_Final.git"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")


#Loading Styling Options
mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 16,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.text.x = element_text(size = 14))
}

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 16,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}

#Loading Quantile Break Functions
qBr <- function(df, variable, rnd) {
 if (missing(rnd)) {
    as.character(quantile(round(df[[variable]],0),
                 c(.01,.2,.4,.6,.8), na.rm=T))
 } else if (rnd == FALSE | rnd == F) {
    as.character(formatC(quantile(df[[variable]],
                 c(.01,.2,.4,.6,.8), na.rm=T), digits = 3))
 }
}


q5 <- function(variable) {as.factor(ntile(variable, 5))}

#Loading Hexadecimal Color Palette

palette5 <- c("#324376", "#586ba4", "#f5dd90", "#ee964b", "#f95738")
palette4 <- c("#324376", "#586ba4", "#ee964b", "#f95738")
palette2 <- c("#324376", "#f95738")

```


<br />

## 2. Data Wrangling



<br />

### 2.1. Import Rail Delay Data



```{r rail_delay_data, cache = TRUE, message = FALSE, warning = FALSE, fig.align='center'}

# January for training and 2-3 weeks in February for testing
rail_2020_01 <- read.csv(unz('Data/2020_01.csv.zip','2020_01.csv'), header = T)
rail_2020_02 <- read.csv(unz('Data/2020_02.csv.zip','2020_02.csv'), header = T)

rail <- rbind(rail_2020_01, rail_2020_02) %>%
  mutate(schedule60 = floor_date(ymd_hms(scheduled_time), unit = "hour"),
         actual60 = floor_date(ymd_hms(actual_time), unit = "hour"),
         week = week(schedule60),
         dotw = wday(schedule60, label=TRUE),
         year = year(schedule60),
         month = month(schedule60)) %>%
  drop_na(delay_minutes)
  #filter(week %in% c(14:18))


summary_statistics <- 
  cbind(" " = list( "mean", "median", "min", "max"),
        "Delay_minutes" = list( "mean" = mean(rail$delay_minutes),
                                "median" = median(rail$delay_minutes),
                                "min" = min(rail$delay_minutes),
                                "max" = max(rail$delay_minutes)),
        "Dalay_hours" = list("mean" = mean(rail$delay_minutes/60),
                             "median" = median(rail$delay_minutes/60),
                             "min" = min(rail$delay_minutes/60),
                             "max" = max(rail$delay_minutes/60))) %>% 
  as_data_frame() 

summary_statistics %>% 
  kable() %>% 
  kable_styling()
```




```{r rail_delay_histogram, cache = TRUE, message = FALSE, warning = FALSE, fig.align='center', fig.width=15}
ggplot(rail)+
  geom_histogram(aes(delay_minutes), binwidth = 0.5, fill = palette2[2], alpha=0.8)+
  #xlim(0, 100) +
  labs(title="NJ Transit and Amtrak rail delayed hours",
       subtitle = "New Jersey, Jan. - Feb., 2020",
       x="Minues", 
       y="Frequency",
       caption="Figure 2.1")+
  plotTheme()
```


```{r rail_delay_histogram_break, cache = TRUE, message = FALSE, warning = FALSE, fig.align='center', fig.width=15}
ggarrange(ncol=3,
          ggplot(subset(rail, delay_minutes<=10))+
            geom_histogram(aes(delay_minutes), binwidth = 0.5, fill = palette2[2], alpha=0.8)+
            #xlim(0, 100) +
            labs(x="Minutes", 
                 y="Frequency",
                   title="Delay time of trains at New Jersey Transit stations, Jan. - Feb. 2020",
                   subtitle="within 10 minutes",
                 caption="Figure 2.2")+
            plotTheme(),
            ggplot(subset(rail, delay_minutes<=60 & delay_minutes > 10))+
              geom_histogram(aes(delay_minutes), binwidth = 0.5, fill = palette2[2], alpha=0.8)+
              #xlim(0, 100) +
              labs(x="Minutes", 
                   y="Frequency",
                   title=" ",
                   subtitle="10 minutes - 1 hour",
                   caption=" ")+
              plotTheme(),
            ggplot(subset(rail, delay_minutes > 60))+
              geom_histogram(aes(delay_minutes), binwidth = 0.5, fill = palette2[2], alpha=0.8)+
              #xlim(0, 100) +
              labs(x="Minutes", 
                   y="Frequency",
                   title=" ",
                   subtitle="over 1 hour",
                   caption=" 2")+
              plotTheme())

```



### 2.2. Import Weather Data



```{r weather_data, cache = TRUE, message = FALSE, warning = FALSE, fig.align='center'}

#https://mesonet.agron.iastate.edu/request/download.phtml?network=CA_ASOS
# EWR station is at Newark International Airport
weather.Data <- 
  riem_measures(station = "EWR", date_start = "2020-01-01", date_end = "2020-03-01") 


weather.Panel <-  
  weather.Data %>%
    mutate_if(is.character, list(~replace(as.character(.), is.na(.), "0"))) %>% 
    replace(is.na(.), 0) %>%
    mutate(interval60 = ymd_h(substr(valid, 1, 13))) %>%
    mutate(week = week(interval60),
           dotw = wday(interval60, label=TRUE)) %>%
    group_by(interval60) %>%
    summarize(Temperature = max(tmpf),
              Percipitation = sum(p01i),
              Wind_Speed = max(sknt)) %>%
    mutate(Temperature = ifelse(Temperature == 0, 42, Temperature))



grid.arrange(bottom="Figure 2.2 Weather Data, New Jersey, January - February, 2020",
  ggplot(weather.Panel, aes(interval60, Percipitation)) +
    geom_line(color = palette2[2]) + 
    labs(title="Percipitation", x="Hour", y="Percipitation") + 
    plotTheme(),
  ggplot(weather.Panel, aes(interval60, Wind_Speed)) + 
    geom_line(color = palette2[2]) + 
    labs(title="Wind Speed", x="Hour", y="Wind Speed") + 
    plotTheme(),
  ggplot(weather.Panel, aes(interval60, Temperature)) + 
    geom_line(color = palette2[2]) + 
    labs(title="Temperature", x="Hour", y="Temperature") + 
    plotTheme())
```



### 2.3. Import Station and Place Data


```{r station_data, cache = TRUE, message = FALSE, warning = FALSE, results = FALSE, fig.align='center'}
station.sf <- st_read("https://opendata.arcgis.com/datasets/4809dada94c542e0beff00600ee930f6_0.geojson") %>%
  st_transform("EPSG:3424") %>% #NAD83 / New Jersey (ftUS) 
  rename(STATION_NAME = STATION_ID)

station_list <- read.csv('Data/StationName_ID.csv', header = T)
station.sf <- left_join(station.sf, station_list, by=c("STATION_NAME" = "STATION_NAME"))


# mainly New Jersey yet a few in New York State and Penn
counties <- rbind(get_acs(geography = "county", 
                        year = 2019,
                        state = 34, 
                        variables = (TotalPop = 'B01001_001E'),
                        survey = "acs5",
                        output = "wide",
                        geometry = TRUE),
                get_acs(geography = "county", 
                        year = 2019,
                        state = 42, 
                        variables = (TotalPop = 'B01001_001E'),
                        survey = "acs5",
                        output = "wide",
                        geometry = TRUE),
                get_acs(geography = "county", 
                        year = 2019,
                        state = 36,
                        variables = (TotalPop = 'B01001_001E'),
                        survey = "acs5",
                        output = "wide",
                        geometry = TRUE)) %>% 
  st_transform(st_crs(station.sf)) 
 
intersect.counties <-  subset(counties, GEOID %in% 
                              (st_intersection(counties, station.sf) %>%
                                 dplyr::select(GEOID) %>%
                                 st_drop_geometry() %>%
                                 unique())$GEOID)

rm(counties)

states <- rbind(get_acs(geography = "state", 
                        year = 2019,
                        state = 34, 
                        variables = (TotalPop = 'B01001_001E'),
                        survey = "acs5",
                        output = "wide",
                        geometry = TRUE),
                get_acs(geography = "state", 
                        year = 2019,
                        state = 42, 
                        variables = (TotalPop = 'B01001_001E'),
                        survey = "acs5",
                        output = "wide",
                        geometry = TRUE),
                get_acs(geography = "state", 
                        year = 2019,
                        state = 36,
                        variables = (TotalPop = 'B01001_001E'),
                        survey = "acs5",
                        output = "wide",
                        geometry = TRUE)) %>% 
  st_transform(st_crs(station.sf)) 

```



```{r station_plot, cache = TRUE, message = FALSE, warning = FALSE, fig.width=9, fig.align='center'}
# ggplot() +
#   geom_sf(data=intersect.counties, color='grey', fill=NA) +
#   geom_sf(data=station.sf, color=palette2[1], alpha=0.8, size=1) +
#   labs(title="New Jersey Transit and Amtrak Stations",
#        caption = "Figure 2.1") +
#   mapTheme() 

station.sf %>% st_transform(crs = 4326) %>%
  st_coordinates() %>% leaflet() %>% addProviderTiles("Thunderforest.Landscape") %>% addProviderTiles("Stamen.TonerHybrid") %>% addMarkers(icon = list(iconSize = c(0.5, 0.5)))
```


### 2.4. Create Space-Time Panel and Time Lags


```{r bike_panel, cache = TRUE, message = FALSE, warning = FALSE}
# rail.template <- rail %>%
#   semi_join(st_drop_geometry(station.sf), 
#             by = c( "to_id" = "STATION_ID"))
# 
# length(unique(rail.template$schedule60)) * length(unique(rail.template$to_id))
# 
# study.panel <- 
#   expand.grid(schedule60 = unique(rail.template$schedule60), 
#               to_station = unique(rail.template$to_id)) 
# 
# nrow(study.panel)      
# 
# 
# rail.panel <- 
#   rail.template %>%
#     mutate(Train_Counter = 1) %>%
#     right_join(study.panel) %>% 
#       group_by(schedule60, to, to_id) %>% 
#       summarize(Train_Count = sum(Train_Counter, na.rm=T)) %>%
#       left_join(weather.Panel, by = c( "schedule60" = "interval60")) %>%
#         left_join(station.sf, by = c( "to_id" = "STATION_ID")) %>%
#           mutate(week = week(schedule60),
#                  dotw = wday(schedule60, label = TRUE)) # %>% st_sf()
# 
# 
# rail.panel <- 
#   rail.panel %>% 
#     arrange(to_station, schedule60) %>% 
#     group_by(to_station) %>% 
#     mutate(lagHour = dplyr::lag(Trip_Count,1),
#            lag2Hours = dplyr::lag(Trip_Count,2),
#            lag3Hours = dplyr::lag(Trip_Count,3),
#            lag4Hours = dplyr::lag(Trip_Count,4),
#            lag12Hours = dplyr::lag(Trip_Count,12),
#            lag1day = dplyr::lag(Trip_Count,24)) %>% 
#    ungroup()

```




## 3. Exploratory Analysis


PPM – the percentage of trains arriving at their destination within 5 minutes of schedule

```{r ppm, cache = TRUE, message = FALSE, warning = FALSE}

ppm_summary <- data_frame(var = c("all_pp5", "all_pp10", "all_pp20"), 
                          val = c(
                                 round(nrow(subset(rail, delay_minutes<5))/nrow(rail)*100, digits=2),
                                 round(nrow(subset(rail, delay_minutes<10))/nrow(rail)*100, digits=2),
                                 round(nrow(subset(rail, delay_minutes<20))/nrow(rail)*100, digits=2)))

ppm_summary[,2] %>%  
  `rownames<-`(., c("Arrived within 5 minutes", "Arrived within 10 minutes",
                    "Arrived within 20 minutes")) %>% 
  kable(col.names = c("Percentage of trains")) %>% kable_styling()

```



```{r ppm plots, cache = TRUE, message = FALSE, warning = FALSE, fig.width=15}
station.sf <- rail %>% group_by(to) %>%
    summarise(train_count = n(),
              mean_delay_minutes = mean(delay_minutes),
              ppm_5 = count_if(lt(5), delay_minutes)/train_count,
              ppm_10 = count_if(lt(10), delay_minutes)/train_count,
              ppm_20 = count_if(lt(20), delay_minutes)/train_count) %>% 
    right_join(station.sf, by = c( "to" = "STATION_NAME")) %>%  
    st_sf() %>%
    st_transform(crs = 4326) 



ggarrange(ncol=3,
    ggplot() +
      geom_sf(data=intersect.counties, color='grey', fill=NA) +
      geom_sf(data=na.omit(station.sf), aes(color=ppm_5), size=2) +
        scale_color_gradient(high = "#FFFFFF", low = palette5[5],
                             name="PPM 5 minutes") + 
      labs(title="Pertuality Rate of Trains by Station",
           subtitle="Jan. - Feb. 2020",
           caption = "Figure 3.1") +
      mapTheme(),
    ggplot() +
      geom_sf(data=intersect.counties, color='grey', fill=NA) +
      geom_sf(data=na.omit(station.sf), aes(color=ppm_10), size=2) +
        scale_color_gradient(high = "#FFFFFF", low = palette5[5],
                             name="PPM 10 minutes") + 
      labs(title=" ",
           subtitle=" ",
           caption = " ") +
      mapTheme(),
    ggplot() +
      geom_sf(data=intersect.counties, color='grey', fill=NA) +
      geom_sf(data=na.omit(station.sf), aes(color=ppm_20), size=2) +
        scale_color_gradient(high = "#FFFFFF", low = palette5[5],
                             name="PPM 20 minutes") + 
      labs(title=" ",
           subtitle=" ",
           caption = " ") +
      mapTheme())

```





## 4. Modeling and Validation







## 5. Conclusion





